#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
#jupyter nbextension enable python-markdown/main

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
#jupyter trust final_notebook.ipynb

# Install a JupyterLab extension for handling widgets
# requires nodejs -- https://nodejs.org/en/
jupyter labextension install @jupyter-widgets/jupyterlab-manager